FROM python:3.11-slim

RUN useradd --create-home appuser

WORKDIR /app

COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

USER appuser

CMD ["gunicorn","--bind","0.0.0.0:5000","app:app"]